"""Add created_at to Post

Revision ID: 220164680386
Revises: 9e1d970585e9
Create Date: 2026-01-03 23:36:48.109685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220164680386'
down_revision = '9e1d970585e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
