"""Add vk_layout to Post

Revision ID: 4025e0541920
Revises: a16f54b881c6
Create Date: 2025-11-11 07:53:16.864304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4025e0541920'
down_revision = 'a16f54b881c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vk_layout', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('vk_layout')

    # ### end Alembic commands ###
