"""Add timezone and tariff

Revision ID: 9e1d970585e9
Revises: 4025e0541920
Create Date: 2025-12-19 23:46:02.394096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1d970585e9'
down_revision = '4025e0541920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tariff', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_setup_complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_setup_complete')
        batch_op.drop_column('tariff')
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
