"""Sync database to current models

Revision ID: a16f54b881c6
Revises: 
Create Date: 2025-11-10 14:21:34.859991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16f54b881c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_vk_refresh_token_encrypted', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('vk_device_id', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('vk_token_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_tokens', schema=None) as batch_op:
        batch_op.drop_column('vk_token_expires_at')
        batch_op.drop_column('vk_device_id')
        batch_op.drop_column('_vk_refresh_token_encrypted')

    # ### end Alembic commands ###
